### PR TITLE
Delete change_listener docs after delay if database not found

### LINKED ISSUE #112: Change listener doesn't handle a deleted source database
Hi again!

In my application we run a per-user database model where we create and destroy CouchDB databases from time to time as user accounts are created and destroyed.

I've noticed that whenever a CouchDB database is deleted, the Spiegel update listener picks up the change (in this case, that the database is deleted), but then the Spiegel change listener continuously retries to process that database but fails with a "Database does not exist" exception.

I believe it should detect that error condition and remove the associated record from the ```spiegel``` couchdb database to prevent continuous retries, in the same way that it correctly detects the creation of a new CouchDB database and adds the record.

Here's an excerpt from the logs with the backtrace.  This is on ```v.1.0.3``` but was also occurring on older versions.

Thanks again for the great work on Spiegel.

```
{
"name": "spiegel",
"hostname": "47d7445f206c",
"pid": 6,
"level": 50,
"err": {
"message": "reason=Database does not exist., error=not_found, arguments=[{\"url\":\"http://admin:xxxxxxx@couchdb:5984/source-db/_changes\",\"qs\":{\"since\":\"45-g1AAAAIbeJyV0M0NgjAYBuDGnwAHZ9ARaAuFnmQT7Q8ECZaDetZNdBPdRDfB0pJgNCT10iZf-j5t3xoA4JdTCRaqUY3MM9WUzeFY6_GEAb5s27Yqp2y-1wMP4QLTsPg-PBLnK73ydS8AI8SQYEG4BMFJybzYqVyOpbMuvenTgUmneYRhQl3v33bCuRc8IwhYREmEHAU10yu46E0j107xjcJgiCB07cEqN6vchy4E5SER1KELKzys8Bx-kzAkSAr_esfLKh-txoISjH-U6g3dpqNg\",\"include_docs\":true,\"limit\":1},\"parseBody\":true}]",
"name": "Error",
"stack": "Error: reason=Database does not exist., error=not_found, arguments=[{\"url\":\"http://admin:xxxxxxx@couchdb:5984/source-db/_changes\",\"qs\":{\"since\":\"45-g1AAAAIbeJyV0M0NgjAYBuDGnwAHZ9ARaAuFnmQT7Q8ECZaDetZNdBPdRDfB0pJgNCT10iZf-j5t3xoA4JdTCRaqUY3MM9WUzeFY6_GEAb5s27Yqp2y-1wMP4QLTsPg-PBLnK73ydS8AI8SQYEG4BMFJybzYqVyOpbMuvenTgUmneYRhQl3v33bCuRc8IwhYREmEHAU10yu46E0j107xjcJgiCB07cEqN6vchy4E5SER1KELKzys8Bx-kzAkSAr_esfLKh-txoISjH-U6g3dpqNg\",\"include_docs\":true,\"limit\":1},\"parseBody\":true}]\nat EnhancedRequest._newError (/usr/local/lib/node_modules/spiegel/node_modules/couch-slouch/scripts/enhanced-request.js:84:11)\nat /usr/local/lib/node_modules/spiegel/node_modules/couch-slouch/scripts/enhanced-request.js:150:18\nat tryCatcher (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/util.js:16:23)\nat Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/promise.js:512:31)\natPromise._settlePromise (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/promise.js:569:18)\nat Promise._settlePromise0 (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/promise.js:614:10)\nat Promise._settlePromises (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/promise.js:693:18)\nat Promise._fulfill (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/promise.js:638:18)\nat Request._callback (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/nodeback.js:42:21)\nat Request.self.callback (/usr/local/lib/node_modules/spiegel/node_modules/request/request.js:186:22)\nat Request.emit (events.js:160:13)\nat Request.<anonymous> (/usr/local/lib/node_modules/spiegel/node_modules/request/request.js:1163:10)\nat Request.emit (events.js:160:13)\nat IncomingMessage.<anonymous> (/usr/local/lib/node_modules/spiegel/node_modules/request/request.js:1085:12)\nat Object.onceWrapper (events.js:255:19)\nat IncomingMessage.emit (events.js:165:20)"
},
"msg": "reason=Database does not exist., error=not_found, arguments=[{\"url\":\"http://admin:xxxxxxx@couchdb:5984/source-db/_changes\",\"qs\":{\"since\":\"45-g1AAAAIbeJyV0M0NgjAYBuDGnwAHZ9ARaAuFnmQT7Q8ECZaDetZNdBPdRDfB0pJgNCT10iZf-j5t3xoA4JdTCRaqUY3MM9WUzeFY6_GEAb5s27Yqp2y-1wMP4QLTsPg-PBLnK73ydS8AI8SQYEG4BMFJybzYqVyOpbMuvenTgUmneYRhQl3v33bCuRc8IwhYREmEHAU10yu46E0j107xjcJgiCB07cEqN6vchy4E5SER1KELKzys8Bx-kzAkSAr_esfLKh-txoISjH-U6g3dpqNg\",\"include_docs\":true,\"limit\":1},\"parseBody\":true}]",
"time": "2018-02-12T05:21:12.370Z",
"src": {
"file": "/usr/local/lib/node_modules/spiegel/src/process.js",
"line": 309,
"func": "_onError"
},
"v": 0
}
```

### PR DESCRIPTION
**Pull request by jjd314**
Fixes #112 

Does not yet have any tests, since I could not easily figure out how to add them.  Any advice would be welcome.

Still has a slight issue, in that it logs 10 or 12 error messages per second (on my machine) for the 5 minutes (configurable) that it is waiting before deciding to delete the change_listener.  Perhaps #53 can be leveraged to avoid that, once someone (maybe me) finishes it?

### CODE REVIEW

File: src/change-listeners.js [hunk 1]
```diff
@@ -198,6 +200,13 @@ class ChangeListeners extends Process {
     }
   }
 
+  async destroy(dbNames) {
```
Comment (redgeoff) [inline src/change-listeners.js]: Is this destroy function being used?

File: src/change-listeners.js [hunk 2]
```diff
@@ -269,6 +283,9 @@ class ChangeListeners extends Process {
     try {
       await this._processBatchOfChanges(listener)
     } catch (err) {
+      if(err instanceof DatabaseNotFoundError) {
```
Comment (redgeoff) [inline src/change-listeners.js]: Is there a reason that we need this if check here?

File: src/change-listeners.js [hunk 3]
```diff
@@ -198,6 +200,13 @@ class ChangeListeners extends Process {
...
   }
 
+  async destroy(dbNames) {
+    let listeners = await this._getByDBNames(dbNames)
+    listeners.map(async (listener) => {
+      await this._getAndDestroy(listener._id)
+    })
+  }
+
   _processChange(change, dbName, requests) {
```
Comment (redgeoff) [inline src/change-listeners.js]: I'd recommend adding a unit test to _changesForListener in https://github.com/redgeoff/spiegel/blob/master/test/spec/change-listeners.js that stubs _changesArray to generate an not_found error and then check for the DatabaseNotFoundError. (This project uses sinon for mocking)

File: src/process.js [hunk 4]
```diff
@@ -264,14 +269,28 @@ class Process extends events.EventEmitter {
...
+  _isProbablyDeleted(item) {
+    // Can't really tell if a database has been deleted or just hasn't been
+    //  replicated to our node yet.  Compromise by deleting the item
+    //  if updated_at is long ago enough
+    return (
+      new Date().getTime() - new Date(item.updated_at).getTime() > this._assumeDeletedAfterSeconds * 1000
+    )
+  }
+
   async _processAndUnlockIfError(item) {
```
Comment (redgeoff) [inline src/process.js]: I'd recommend adding a unit test for _processAndUnlockIfError in https://github.com/redgeoff/spiegel/blob/master/test/spec/process.js that stubs _process to throw a DatabaaseNotFoundError and then use a spy to make sure _getAndDestroy is called

**Comment by redgeoff** [comment]
Great work! I've added some review comments to the code and here are some other comments:
1. I think you'll also need to modify https://github.com/redgeoff/spiegel/blob/master/src/cl-params.js to add `assume-deleted-after-seconds`
2. Can you please modify https://github.com/redgeoff/spiegel/blob/master/bin/usage.txt to include details about the new `assume-deleted-after-seconds` 
3. It looks like the lint test is failing. You can use `npm run lint` to see the errors. You may also need to consider https://github.com/redgeoff/spiegel/blob/master/TESTING.md#beautify
4. Yes, #53 should provide a nice enhancement!

File: src/change-listeners.js (hunk 1 above)
Comment (jjd314) [reply src/change-listeners.js]: No.  That's just cruft from an initial, ill-advised attempt.  I'll clean it out.

File: src/change-listeners.js (hunk 2 above)
Comment (jjd314) [reply src/change-listeners.js]: Without it, the DatabaseNotFoundError is swallowed by the rest of the catch handler, rather than being handled by the caller.  I suppose I could rethrow all errors, but that seemed an unnecessary breaking change.

**Comment by jjd314** [comment]
Thanks for the review and comments!  I've addressed everything but the tests, which I'll work on now and then commit the lot for another review.

BTW, I went with 'assume-deleted-after' instead of 'assume-deleted-after-seconds', in keeping with the existing 'retry-after'.

**Comment by jjd314** [comment]
Apparently I did not provide enough code coverage in my tests.  Do I need to test every internal method I changed to make sure it is throwing errors appropriately?

**Comment by redgeoff** [comment]
Yeah, Spiegel requires 100% code coverage (for good reasons). Take a look at https://github.com/redgeoff/spiegel/blob/master/TESTING.md#test-in-node. You should be able to run `npm run node-full-test` and then see what lines are untested by opening cache/coverage/node/lcov-report/index.html in a browser.

File: src/change-listeners.js [hunk 5]
```diff
@@ -269,6 +276,9 @@ class ChangeListeners extends Process {
     try {
       await this._processBatchOfChanges(listener)
     } catch (err) {
+      if (err instanceof DatabaseNotFoundError) {
```
Comment (redgeoff) [inline src/change-listeners.js]: I think we probably want this if block below the `this._onError(err)` line so that the error is logged, etc...

**Comment by redgeoff** [comment]
This all looks good, except the one new comment I just added. Thanks for the hard work on this!

File: src/change-listeners.js (hunk 5 above)
Comment (redgeoff) [reply src/change-listeners.js]: Oh, nice catch! No, this looks good. I'll merge this now

**Comment by redgeoff** [comment]
The only thing I can think of is like what you mentioned: add something like a `error_at` that is set when the error is first reported and then used instead of `updated_at`. (Of course, `error_at` would need to be cleared if a later try was successful)
